"""create resource table

Revision ID: a3f8fc43996d
Revises:
Create Date: 2023-02-19 00:44:24.238756

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a3f8fc43996d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resource_id"), "resource", ["id"], unique=False)
    op.create_index(op.f("ix_resource_name"), "resource", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resource_name"), table_name="resource")
    op.drop_index(op.f("ix_resource_id"), table_name="resource")
    op.drop_table("resource")
    # ### end Alembic commands ###
