"""non nullable resource fields

Revision ID: 8462259edbcf
Revises: e45c23a5d30e
Create Date: 2023-02-18 12:31:27.787748

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8462259edbcf"
down_revision = "e45c23a5d30e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("resource", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("resource", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
